name: Tests

on:
  push:
    branches: [ '*' ] 
  pull_request:
    branches: [ master ]
    
jobs:
  run_unit_test:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2 
      - uses: pip install pycodestyle
      - run: |
          cd test/unit-test
          python -m unittest test_my_utils.py
          
  run_func_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: pip install pycodestyle
      - run: |
          cd test/func-test
          bash test_print_fires.sh